const P=[
{id:"whitening-serum",n:"Whitening Serum",s:"50ml",p:1000,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804964/Whitening_serum_-_Price_1000_-_50ml_mxv3rv.png"},
{id:"whitening-cream",n:"Whitening Cream",s:"100ml",p:800,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804964/Whitening_cream_-_Price_800_-_100ml_lobdi1.png"},
{id:"oil-control-facewash",n:"Oil Control Facewash",s:"120ml",p:800,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804962/Oil_control_face_wash_-_Price_800_-_120ml_n6upq8.png"},
{id:"vitamin-e-bead-facewash",n:"Active Vitamin E Bead Facewash",s:"120ml",p:800,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804962/Active_vitamin_E_bead_-_Facewash_-_Price_800_-_120ml_j4tz3k.png"},
{id:"scrubbing-facewash",n:"Scrubbing Facewash",s:"120ml",p:1000,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804961/Scrubbing_face_wash_-_Price_1000_-_120ml_os4nr9.png"},
{id:"vitamin-c-facewash",n:"Vitamin C Facewash",s:"120ml",p:800,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804961/Vitamin_C_facewash_-_Price_800_-_120ml_x2t51g.png"},
{id:"fairness-cream",n:"Fairness Cream",s:"50ml",p:600,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804961/Fairness_cream_-_Price_600_-_50ml_bv0gll.png"},
{id:"gold-facial-kit",n:"Gold Facial Kit",s:"Kit",p:12000,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804959/Gold_facial_kit_-_Price_12000_cjdrxc.png"},
{id:"creamy-facewash",n:"Creamy Facewash",s:"120ml",p:1000,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804959/Creamy_facewash_-_Price_1000_-_120ml_kydqzl.png"},
{id:"hair-serum",n:"Hair Serum",s:"100ml",p:1500,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804958/Hair_serum_-Price_1500_-_100_ml_us9jx4.png"},
{id:"acne-facewash",n:"Acne Facewash",s:"120ml",p:800,img:"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790804959/Acne_Facewash_-_Price_800_-_120ml_amackp.png"}];
const SV={"Facial":[["Clean Up",500],["Skin Polish",1000],["Whitening Facial",1500],["Gold Facial",2500],["Diamond Facial",3000]],
"Threading & Wax":[["Eyebrow",200],["Upper Lips",100],["Full Face Wax",800],["Arms Wax",800],["Full Legs Wax",1000]],
"Hair":[["Hair Cut",1000],["Step Cut",1000],["Hair Wash",500]],
"Makeup":[["Soft Party Makeup",3000],["Party Makeup",2500],["Model Makeup",3000],["Engagement Makeup",5000],["Bridal Makeup","15,000–25,000"]]};
const $=s=>document.querySelector(s),rs=n=>"Rs. "+n.toLocaleString("en-US");
const WA="https://wa.me/923010005466?text=",MAP="https://maps.app.goo.gl/RHCRRWzLo6FZPFsBA";
const MSG={book:"Hi Saba Beauty Saloon, I would like to book an appointment.",bridal:"Hi Saba Beauty Saloon, I would like to inquire about bridal makeup."};
const wa=k=>WA+encodeURIComponent(MSG[k]||k);
// ---- images with replaceable fallback ----
const im=(src,label,cls="")=>`<div class="imgbox" style="width:100%;height:100%"><img src="${src}" alt="${label}" loading="lazy" onerror="this.parentNode.innerHTML='<div class=&quot;ph ${cls}&quot;><span>${label}</span></div>'"></div>`;
const SVI={"Facial":"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790807811/FACIAL_e5czlc.png","Threading & Wax":"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790807808/THREADING_WAX_hba99z.png","Hair":"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790807807/HAIR_uu0dub.png","Makeup":"https://res.cloudinary.com/dy4yjeeib/image/upload/v1790807807/MAKEUP_iqrrou.png"};
const gi=(k,l)=>im("images/gallery/"+k+".jpg",l+" image","g");
const HS=[["https://res.cloudinary.com/bq5gruwo/image/upload/v1790773123/1d.png","https://res.cloudinary.com/bq5gruwo/image/upload/v1790773055/1.png"],["https://res.cloudinary.com/bq5gruwo/image/upload/v1790773123/2d.png","https://res.cloudinary.com/bq5gruwo/image/upload/v1790773056/2.png"],["https://res.cloudinary.com/bq5gruwo/image/upload/v1790773125/3d.png","https://res.cloudinary.com/bq5gruwo/image/upload/v1790773056/3.png"]];
const HERO_TEXT=true; // set false if your slide images already contain the heading
// ---- templates ----
const AR='<svg viewBox="0 0 24 24"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
const WI='<svg viewBox="0 0 24 24"><path d="M4 20l1.3-4A8 8 0 1 1 8 18.7z"/></svg>';
const card=p=>`<div class="card fade"><a class="im" href="/product/${p.id}">${im(p.img,p.n)}</a><h3>${p.n}</h3><div class="sz">${p.s}</div><div class="row"><span class="pr">${rs(p.p)}</span><button class="add" aria-label="Add to cart" onclick="add('${p.id}')"><svg viewBox="0 0 24 24"><path d="M5 8h14l-1 12H6zM9 8a3 3 0 0 1 6 0"/></svg></button></div></div>`;
const T={
home:()=>`<section class="hs" id="hs">${HS.map((h,k)=>`<picture class="sl${k?'':' on'}"><source media="(max-width:700px)" srcset="${h[1]}"><img src="${h[0]}" alt="Saba Cosmetics" ${k?'loading="lazy"':''}></picture>`).join("")}${HERO_TEXT?`<div class="tint"></div><div class="hc wrap"><span class="eye">Saba Cosmetics</span><h1>Skincare<br>That Works<br><em style="font-style:italic">With You.</em></h1><p>Premium skincare essentials crafted with care to keep your skin fresh, healthy and radiant.</p><div class="btns"><a class="btn cr" style="color:var(--ink)" href="/shop">Shop All Products ${AR}</a><a class="btn" style="color:#fff;border-color:#fff" href="/services">View Services</a></div></div>`:""}<div class="dots">${HS.map((h,k)=>`<button class="${k?'':'on'}" aria-label="Slide ${k+1}" onclick="hsTo(${k})"></button>`).join("")}</div></section><div class="wrap hb"><div class="trust"><span><b>Quality</b>Formulations</span><span><b>For Healthy</b>Radiant Skin</span><span><b>Trusted by</b>Our Clients</span></div></div>
<section style="padding-top:20px"><div class="wrap"><div class="sh"><div><span class="eye">Our Products</span><h2>Best Sellers.</h2></div><a class="lnk" href="/shop">View All Products →</a></div><div class="grid">${P.slice(0,4).map(card).join("")}</div></div></section>
<section class="dark"><div class="wrap dg"><div class="fade"><h2>Complete<br><em style="font-style:italic;color:var(--cream)">Skincare Range</em></h2><p>From cleansers to creams, explore the full Saba Cosmetics range and build your perfect routine.</p><a class="btn cr" style="color:var(--ink)" href="/shop">Explore All Products ${AR}</a></div></div></section>
<section><div class="wrap"><div class="svh fade"><div><span class="eye">Our Services</span><h2>Professional<br>Beauty <em style="font-style:italic">Services.</em></h2></div><div class="svr"><p>From everyday grooming to bridal makeovers, we offer a range of beauty services designed to make you look and feel your best.</p><a class="btn dk" data-wa="book">Book Appointment ${WI}</a></div></div><div class="sc">${[["Facial","From Rs. 500"],["Threading & Wax","From Rs. 100"],["Hair","From Rs. 500"],["Makeup","From Rs. 2,500"]].map((s,n)=>`<a class="fade" href="/services"><div class="im">${im(SVI[s[0]],s[0]+" image","g")}</div><span class="no">0${n+1}</span><i class="go"><svg viewBox="0 0 24 24"><path d="M7 17 17 7M8 7h9v9"/></svg></i><div class="ov"><b>${s[0]}</b><span>${s[1]}</span></div></a>`).join("")}</div></div></section>
<div class="br"><div class="t fade"><span class="eye">Bridal Makeup</span><h2>Your Day.<br><em style="font-style:italic">Your Look.</em></h2><p>Bridal beauty crafted for your most important moments.</p><a class="btn dk" data-wa="bridal">Book Bridal Appointment ${WI}</a></div><div class="im">${gi("bridal-feature","Bridal image")}</div></div>
<section><div class="wrap"><div class="sh"><h2>Beauty in Every<br>Detail.</h2><a class="lnk" href="/gallery">View Gallery →</a></div>${gal(1)}</div></section>
<section style="padding-top:0"><div class="wrap about"><h2>Beauty, Care &amp;<br>Confidence.</h2><p>Saba Beauty Saloon brings together professional beauty services and everyday skincare essentials under one name. From salon treatments and makeup to Saba Cosmetics products, every part of the experience is designed around beauty, care and confidence.</p></div></section>
${ctaS()}`,
shop:()=>`<div class="wrap pt"><span class="eye">Saba Cosmetics</span><h1 style="font-size:clamp(2.4rem,5.5vw,4rem)">Shop.</h1></div><div class="wrap" style="padding-bottom:100px"><div class="grid">${P.map(card).join("")}</div></div>`,
product:id=>{const p=P.find(x=>x.id===id)||P[0];return`<div class="wrap pt"><a class="lnk" href="/shop">← Shop</a></div><div class="wrap pd" style="padding-bottom:100px"><div class="im">${im(p.img,p.n)}</div><div><span class="eye">Saba Cosmetics</span><h1 style="font-size:clamp(2.4rem,5vw,3.8rem)">${p.n}</h1><div class="pr">${rs(p.p)}</div><p style="color:var(--mut)">Size: ${p.s}</p><div style="margin:26px 0;display:flex;gap:12px;flex-wrap:wrap"><div class="qty"><button onclick="pq(-1)">−</button><span id="pq">1</span><button onclick="pq(1)">+</button></div><button class="btn dk" onclick="add('${p.id}',+$('#pq').textContent)">Add to Cart</button></div>${["Product Benefits","How to Use","Ingredients","Product Details"].map(t=>`<div class="acc"><b>${t}</b><span>Product information coming soon</span></div>`).join("")}</div></div>`},
services:()=>{const D={"Facial":"Deep cleansing and glow-boosting treatments for every skin type.","Threading & Wax":"Clean, precise grooming with smooth, gentle results.","Hair":"Fresh cuts and care to keep your hair healthy and styled.","Makeup":"From soft party looks to full bridal glam."};const E=Object.entries(SV);return`<section class="sph"><div class="wrap fade"><span class="eye">Our Services</span><h1>Beauty Services,<br><em>Priced Simply.</em></h1><p>Professional care for your skin, hair and every special occasion. Pick a service and book on WhatsApp.</p><div class="spt">${E.map(([k],n)=>`<button onclick="document.getElementById('sv-${n}').scrollIntoView({behavior:'smooth',block:'start'})">${k}</button>`).join("")}</div></div></section><div class="wrap spl">${E.map(([k,v],n)=>`<section class="spc fade${n%2?' rev':''}" id="sv-${n}"><div class="spi"><div class="im">${im(SVI[k],k+" image","g")}</div><span class="spn">0${n+1}</span></div><div class="spb"><h3>${k}</h3><p class="spd">${D[k]||""}</p><ul>${v.map(x=>`<li${/Bridal/.test(x[0])?' class="hl"':''}><span>${x[0]}</span><i class="dt"></i><span class="pp">Rs. ${typeof x[1]=="number"?x[1].toLocaleString("en-US"):x[1]}</span></li>`).join("")}</ul><a class="btn dk" data-wa="book">Book ${k} ${WI}</a></div></section>`).join("")}</div>${ctaS()}`},
gallery:()=>{const pool=[["salon",["Facial","Threading & Wax","Hair","Makeup"].map(k=>[SVI[k],k])],["skin",HS.map(h=>[h[0],"Saba Cosmetics"])],["skin",P.map(p=>[p.img,p.n,1])]];const G=[];let more=true,r=0;while(more){more=false;pool.forEach(([c,a])=>{if(a[r]){G.push([c,...a[r]]);more=true}});r++}return`<section class="sph"><div class="wrap fade"><span class="eye">Bridal · Makeup · Hair · Skincare</span><h1>Our <em>Gallery.</em></h1><p>A glimpse of our salon work and the Saba Cosmetics range.</p></div></section><div class="wrap" style="padding-top:56px;padding-bottom:100px"><div class="gf"><button class="on" onclick="gfl('all',this)">All</button><button onclick="gfl('salon',this)">Salon</button><button onclick="gfl('skin',this)">Skincare</button></div><div class="gg">${G.map((g,n)=>`<div class="gt fade${n%5==0?' t':''}${n%7==3?' w':''}${g[3]?' pr':''}" data-c="${g[0]}">${im(g[1],g[2])}<b>${g[2]}</b></div>`).join("")}</div></div>${ctaS()}`},
about:()=>`<section class="sph"><div class="wrap fade"><span class="eye">About Saba</span><h1>Beauty, Care &amp;<br><em>Confidence.</em></h1><p>Professional beauty services and everyday skincare essentials under one name.</p></div></section><div class="wrap ast fade"><div><b>${P.length}</b><span>Skincare Products</span></div><div><b>${Object.keys(SV).length}</b><span>Salon Service Types</span></div><div><b>Daily</b><span>Open 11 AM – 11 PM</span></div></div><div class="wrap spl"><section class="spc fade"><div class="spi"><div class="im">${im(SVI.Makeup,"Saba Beauty Saloon")}</div><span class="spn">01</span></div><div class="spb"><h3>Saba Beauty Saloon</h3><p class="spd">Saba Beauty Saloon brings together professional beauty services and everyday skincare essentials under one name. It is the physical salon in Malir, Karachi, offering facials, threading and wax, hair and makeup, including bridal.</p><a class="btn dk" data-wa="book">Book Appointment ${WI}</a><a class="btn lt" href="/services">View Services</a></div></section><section class="spc rev fade"><div class="spi pc"><div class="im">${im(P.find(x=>x.id=="creamy-facewash").img,"Saba Cosmetics")}</div><span class="spn">02</span></div><div class="spb"><h3>Saba Cosmetics</h3><p class="spd">Saba Cosmetics is its own skincare and cosmetics line. From cleansers to creams and serums, every product is designed around beauty, care and confidence.</p><a class="btn dk" href="/shop">Shop Products</a><a class="btn lt" href="/gallery">View Gallery</a></div></section></div><div class="wrap vals fade"><div><i>01</i><h3>Beauty</h3><p>Professional salon services and skincare made to bring out your best.</p></div><div><i>02</i><h3>Care</h3><p>Thoughtful treatments and products for every skin and hair type.</p></div><div><i>03</i><h3>Confidence</h3><p>Feel great every day, and on your most important occasions.</p></div></div>${ctaS()}`,
contact:()=>`<section class="sph"><div class="wrap fade"><span class="eye">Contact</span><h1>Visit <em>Us.</em></h1><p>Drop by the salon, call us, or book your appointment directly on WhatsApp.</p></div></section><div class="wrap cg"><div class="cc4"><div class="cc fade"><span class="ci"><svg viewBox="0 0 24 24"><path d="M12 21s7-6.2 7-11.5A7 7 0 0 0 5 9.5C5 14.8 12 21 12 21z"/><circle cx="12" cy="9.5" r="2.5"/></svg></span><h4>Address</h4><p>Al Gaffar Nagori Society,<br>Block A, Shop No. 2,<br>Malir, Karachi</p></div><div class="cc fade"><span class="ci"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span><h4>Opening Hours</h4><p>Every Day<br>11:00 AM — 11:00 PM</p></div><a class="cc fade" href="tel:03010005466"><span class="ci"><svg viewBox="0 0 24 24"><path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z"/></svg></span><h4>Call</h4><p>0301 0005466</p></a><a class="cc fade" href="mailto:sababeautysaloon09@gmail.com"><span class="ci"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg></span><h4>Email</h4><p>sababeautysaloon09@gmail.com</p></a><div class="cbt"><a class="btn dk" data-wa="book">Book on WhatsApp ${WI}</a><a class="btn lt" target="_blank" rel="noopener" href="${MAP}">Get Directions</a><a class="btn lt" target="_blank" rel="noopener" href="https://instagram.com/saba.beauty.saloon">Instagram</a></div></div><div class="cm fade"><iframe title="Saba Beauty Saloon map" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=Al%20Gaffar%20Nagori%20Society%20Malir%20Karachi&output=embed"></iframe></div></div>`,
checkout:(C=[])=>`<div class="wrap pt"><h1 style="font-size:clamp(2.4rem,5.5vw,4rem)">Checkout.</h1></div><div class="wrap pd" style="padding-bottom:100px">${C.length?`<form class="fm" onsubmit="event.preventDefault();order()"><input required placeholder="Full name"><input required placeholder="Phone"><input placeholder="Email" type="email"><textarea required rows="3" placeholder="Delivery address"></textarea><p style="color:var(--mut);font-size:13px">Payment: Cash on delivery (payment provider can be connected here later).</p><button class="btn dk" style="justify-content:center">Place Order</button></form><div>${C.map(i=>{const p=P.find(x=>x.id===i.id);return`<div class="it"><div class="im">${im(p.img,p.n)}</div><div><b>${p.n}</b><small>${i.q} × ${rs(p.p)}</small></div></div>`}).join("")}<div class="tot"><span>Subtotal</span><span>${rs(C.reduce((a,i)=>a+P.find(p=>p.id===i.id).p*i.q,0))}</span></div></div>`:`<p>Your cart is empty. <a class="lnk" href="/shop">Shop</a></p>`}</div>`};
function gal(h){if(h)return`<div class="gl gl4">${["Facial","Threading & Wax","Hair","Makeup"].map(k=>`<div class="fade"><b>${k}</b>${im(SVI[k],k+" image","g")}</div>`).join("")}</div>`;return`<div class="gl">${[["bridal","Bridal"],["makeup","Makeup"],["hair","Hair"],["salon","Salon"],["bridal-2","Bridal"]].map(g=>`<div class="fade"><b>${g[1]}</b>${gi(g[0],g[1])}</div>`).join("")}</div>`}
function ctaS(){return`<section class="cta"><div class="wrap fade"><h2>Ready for Your<br>Next Look?</h2><p>Visit Saba Beauty Saloon or book your appointment directly on WhatsApp.</p><div class="btns"><a class="btn dk" data-wa="book">Book on WhatsApp ${WI}</a><a class="btn lt" target="_blank" rel="noopener" href="${MAP}">Get Directions</a></div></div></section>`}
export {P,SV,SVI,HS,WA,MAP,MSG,wa,im,rs,T,gal,ctaS,card};
